# Generated by Django 3.0.8 on 2020-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ownerorclient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
