# Generated by Django 3.0.8 on 2020-09-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_ownerorclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='get_or_return',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
