# Generated by Django 3.0.8 on 2020-08-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200811_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
