# Generated by Django 3.0.8 on 2020-08-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
    ]
