# Generated by Django 3.0.8 on 2020-08-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200811_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Отдел продаж'), (2, 'Отдел контроля')], null=True),
        ),
    ]
