# Generated by Django 3.0.8 on 2020-08-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200816_2121'),
        ('users', '0005_auto_20200814_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basket',
            field=models.ManyToManyField(related_name='basket', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favs', to='products.Product'),
        ),
    ]
