# Generated by Django 3.0.8 on 2020-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200816_2121'),
        ('users', '0006_auto_20200822_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favs', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
