# Generated by Django 3.0.8 on 2020-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200823_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
