# Generated by Django 3.0.8 on 2020-08-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_subcategory',
            old_name='category',
            new_name='subcategory',
        ),
    ]
