# Generated by Django 3.0.8 on 2020-08-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_rented_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rented',
            old_name='is_published',
            new_name='is_rented',
        ),
    ]
