# Generated by Django 3.0.8 on 2020-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20200816_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented',
            name='is_rented',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
