# Generated by Django 3.0.8 on 2020-08-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20200816_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
