# Generated by Django 3.0.8 on 2020-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_delete_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented',
            name='rented_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
