# Generated by Django 3.0.8 on 2020-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_rented_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='is_ended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
