# Generated by Django 3.0.8 on 2020-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_rented_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='get_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rented',
            name='return_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rented',
            name='return_product',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Достовка'), (2, 'Самовывоз')], null=True),
        ),
    ]
