# Generated by Django 3.0.8 on 2020-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20200903_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
