# Generated by Django 3.0.8 on 2020-09-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_rented_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='get_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
