# Generated by Django 3.0.8 on 2020-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_auto_20200908_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rented',
            name='get_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
