# Generated by Django 3.0.8 on 2020-09-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_name'),
        ('products', '0008_product_is_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_14',
        ),
        migrations.AddField(
            model_name='product',
            name='location2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pr2', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pr', to='locations.Location'),
        ),
    ]
