# Generated by Django 3.0.8 on 2020-09-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200903_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location2',
        ),
    ]
