# Generated by Django 3.0.8 on 2020-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
