# Generated by Django 3.0.8 on 2020-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_count_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='get_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
